#-------------------------------------------------------------------SETS--------------------------------------------------------------
# Python Sets
# Sets are one of the four built-in data types in Python used to store collections of data.
# The other three are List, Tuple, and Dictionary, all with different qualities and usage.
# A set is an unordered, mutable collection that does not allow duplicate values.
# Sets are written using curly braces {}.
this_set = {"apple", "banana", "cherry"}
print(this_set)
# Possible Output:
# {'banana', 'apple', 'cherry'}
# Since sets are unordered, the order may vary every time the program runs.
# Characteristics of a Set
# • Unordered
# • Mutable (Items can be added or removed)
# • Does not allow duplicate values
# • Stores only immutable (hashable) objects
# Ordered means that the items have a defined position.
# Since sets are unordered, they do not support indexing or slicing.
this_set = {"apple", "banana", "cherry"}
# print(this_set[0])
# Output:
# TypeError: 'set' object is not subscriptable
# Although sets are mutable, individual items cannot be modified because they are not indexed.
# To change a value, remove the old item and add the new one.
this_set = {"apple", "banana", "cherry"}
this_set.remove("banana")
this_set.add("kiwi")
print(this_set)
# Possible Output:
# {'apple', 'kiwi', 'cherry'}
# Duplicate values are automatically removed by Python.
this_set = {"apple", "banana", "apple", "banana", "cherry"}
print(this_set)
# Output:
# {'apple', 'banana', 'cherry'}
# Sets can contain items of different data types.
mixed_set = {10, 3.14, True, "apple", (1, 2)}
print(mixed_set)
# Possible Output:
# {True, 3.14, 10, 'apple', (1, 2)}
# Lists, dictionaries and sets cannot be stored inside a set because they are mutable.
# Only immutable (hashable) objects can be stored in a set.
# invalid_set = {[1, 2], [3, 4]}
# Output:
# TypeError: unhashable type: 'list'
# Length of a set can be found using the len() function.
this_set = {"apple", "banana", "cherry"}
print(len(this_set))
# Output:
# 3
# Duplicate values are ignored while calculating the length.
this_set = {"apple", "banana", "apple", "banana", "cherry"}
print(len(this_set))
# Output:
# 3
# Type of a set can be found using the type() function.
this_set = {"apple", "banana"}
print(type(this_set))
# Output:
# <class 'set'>
# Sets can also be created using the set() constructor.
# The constructor accepts any iterable such as a list, tuple or string.
fruits = set(["apple", "banana", "cherry"])
print(fruits)
numbers = set((1, 2, 3, 4))
print(numbers)
letters = set("banana")
print(letters)
# Output:
# {'a', 'b', 'n'}
# Duplicate characters are removed automatically.
# Empty sets cannot be created using {} because {} creates an empty dictionary.
empty = {}
print(type(empty))
# Output:
# <class 'dict'>
# To create an empty set, use the set() constructor.
empty = set()
print(type(empty))
# Output:
# <class 'set'>
# Interview Insight:
# Python uses a hash table to implement sets.
# This is why searching, adding and removing elements in a set is generally O(1).
# Accessing Set Items
# Since sets are unordered, they do not support indexing or slicing.
# Therefore, set items cannot be accessed using an index like lists or tuples.
fruits = {"apple", "banana", "cherry"}
# print(fruits[0])
# Output:
# TypeError: 'set' object is not subscriptable
# The only way to access items in a set is by iterating through it or checking
# whether a specific item exists.
# Looping Through a Set
# A for loop is the most common way to access every item in a set.
fruits = {"apple", "banana", "cherry"}
for item in fruits:
    print(item)
# Possible Output:
# banana
# cherry
# apple
# Since sets are unordered, the output order may vary.
# You can also use the enumerate() function while looping.
# Although sets have no indexes, enumerate() assigns a temporary counter.
fruits = {"apple", "banana", "cherry"}
for index, item in enumerate(fruits):
    print(index, item)
# Possible Output:
# 0 banana
# 1 apple
# 2 cherry
# Note:
# The numbers generated by enumerate() are temporary counters.
# They are NOT the actual indexes of the set.
# Checking if an Item Exists
# The 'in' keyword returns True if the specified item exists in the set.
fruits = {"apple", "banana", "cherry"}
print("banana" in fruits)
print("mango" in fruits)
# Output:
# True
# False
# The 'not in' keyword returns True if the specified item does not exist.
fruits = {"apple", "banana", "cherry"}
print("mango" not in fruits)
print("banana" not in fruits)
# Output:
# True
# False
# Membership testing in a set is generally O(1) because Python uses hashing.
# This makes searching in a set much faster than searching in a list for large collections.
# Example
numbers = {10, 20, 30, 40, 50}
if 20 in numbers:
    print("20 is present")
if 60 not in numbers:
    print("60 is not present")
# Output:
# 20 is present
# 60 is not present
# Interview Insight:
# Since sets are unordered, Python cannot answer questions like
# "What is the first element?" or "What is the third element?".
# The only meaningful queries are:
# • Does the element exist?
# • Iterate through all elements.# Adding Set Items
# Since sets are mutable, new items can be added after the set has been created.
# Python provides two methods for adding items:
# • add()    -> Adds a single item.
# • update() -> Adds multiple items.
# add()
# The add() method adds a single item to the set.
# If the item already exists, nothing happens.
fruits = {"apple", "banana", "cherry"}
fruits.add("orange")
print(fruits)
# Possible Output:
# {'banana', 'orange', 'apple', 'cherry'}
# Adding an existing item does not create duplicates.
fruits = {"apple", "banana", "cherry"}
fruits.add("apple")
print(fruits)
# Output:
# {'apple', 'banana', 'cherry'}
# Since duplicate values are not allowed, the set remains unchanged.
# Syntax
set_name.add(item)
# update()
# The update() method adds all elements from another iterable into the set.
# It can accept another set, list, tuple or any iterable.
fruits = {"apple", "banana", "cherry"}
tropical = {"mango", "pineapple", "papaya"}
fruits.update(tropical)
print(fruits)
# Possible Output:
# {'banana', 'papaya', 'apple', 'pineapple', 'mango', 'cherry'}
# Adding items from a list
fruits = {"apple", "banana"}
fruit_list = ["orange", "kiwi"]
fruits.update(fruit_list)
print(fruits)
# Possible Output:
# {'apple', 'banana', 'orange', 'kiwi'}
# Adding items from a tuple
fruits = {"apple", "banana"}
fruit_tuple = ("grapes", "pear")
fruits.update(fruit_tuple)
print(fruits)
# Possible Output:
# {'banana', 'pear', 'apple', 'grapes'}
# Adding items from a string
letters = {"A", "B"}
letters.update("CDE")
print(letters)
# Output:
# {'A', 'B', 'C', 'D', 'E'}
# Strings are iterable, therefore each character is added separately.
# Duplicates are ignored while using update().
numbers = {1, 2, 3}
numbers.update([3, 4, 5, 5, 6])
print(numbers)
# Output:
# {1, 2, 3, 4, 5, 6}
# Syntax
set_name.update(iterable)
# Difference between add() and update()
# add()
# • Adds only one item.
# • Accepts a single object.
fruits = {"apple", "banana"}
fruits.add("orange")
print(fruits)
# Output:
# {'apple', 'banana', 'orange'}
# update()
# • Adds multiple items.
# • Accepts any iterable.
fruits = {"apple", "banana"}
fruits.update(["orange", "kiwi"])
print(fruits)
# Output:
# {'apple', 'banana', 'orange', 'kiwi'}
# Trying to add a list using add() results in an error because lists are mutable.
fruits = {"apple", "banana"}
# fruits.add(["orange", "kiwi"])
# Output:
# TypeError: unhashable type: 'list'
# However, update() works because it adds each element individually.
fruits.update(["orange", "kiwi"])
print(fruits)
# Output:
# {'apple', 'banana', 'orange', 'kiwi'}
# Interview Insight:
# add() inserts one element into the set.
# update() iterates over an iterable and inserts each element individually.
# Therefore, update() can accept lists and tuples, whereas add() cannot.# Removing Set Items
# Python provides five ways to remove items from a set:
# • remove()
# • discard()
# • pop()
# • clear()
# • del
# remove()
# The remove() method removes the specified item from the set.
# If the item does not exist, remove() raises a KeyError.
fruits = {"apple", "banana", "cherry"}
fruits.remove("banana")
print(fruits)
# Output:
# {'apple', 'cherry'}
# Trying to remove an item that does not exist.
fruits = {"apple", "banana", "cherry"}
# fruits.remove("mango")
# Output:
# KeyError: 'mango'
# Syntax
set_name.remove(item)
# discard()
# The discard() method also removes the specified item.
# Unlike remove(), it does not raise an error if the item is not present.
fruits = {"apple", "banana", "cherry"}
fruits.discard("banana")
print(fruits)
# Output:
# {'apple', 'cherry'}
# Removing an item that does not exist.
fruits.discard("mango")
print(fruits)
# Output:
# {'apple', 'cherry'}
# No error is raised.
# Syntax
set_name.discard(item)
# Difference between remove() and discard()
# remove()
# • Raises KeyError if the item does not exist.
# discard()
# • Does not raise any error if the item does not exist.
# This is one of the most commonly asked interview questions related to sets.
# pop()
# The pop() method removes and returns an arbitrary item from the set.
# Since sets are unordered, you cannot predict which item will be removed.
fruits = {"apple", "banana", "cherry"}
removed_item = fruits.pop()
print(removed_item)
print(fruits)
# Possible Output:
# banana
# {'apple', 'cherry'}
# Running the same program again may remove a different item.
# Syntax
set_name.pop()
# clear()
# The clear() method removes all items from the set.
# The set still exists, but becomes empty.
fruits = {"apple", "banana", "cherry"}
fruits.clear()
print(fruits)
# Output:
# set()
# Syntax
set_name.clear()
# del
# The del keyword deletes the entire set object from memory.
fruits = {"apple", "banana", "cherry"}
del fruits
# print(fruits)
# Output:
# NameError: name 'fruits' is not defined
# Unlike clear(), del completely removes the variable.
# clear() vs del
# clear()
# • Removes all items.
# • The set still exists.
# del
# • Deletes the entire set.
# • The variable no longer exists.
# Interview Insight:
# pop() does not remove the "first" or "last" item because sets have no order.
# It removes an arbitrary item chosen by Python.
# Summary
# remove(item)
# Removes the specified item.
# Raises KeyError if the item is absent.
# discard(item)
# Removes the specified item.
# Does nothing if the item is absent.
# pop()
# Removes and returns an arbitrary item.
# clear()
# Removes all items but keeps the set.
# del
# Deletes the entire set object.
# Joining Sets
# Sets can be joined using the following methods:
# • union()
# • update()
# • intersection()
# • intersection_update()
# • difference()
# • difference_update()
# • symmetric_difference()
# • symmetric_difference_update()
# union()
# The union() method returns a new set containing all unique elements
# from both sets. The original sets remain unchanged.
set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}
set3 = set1.union(set2)
print(set3)
# Output:
# {'apple', 'banana', 'cherry', 'google', 'microsoft'}
# Duplicate values are included only once.
# Syntax
set3 = set1.union(set2)
# Multiple sets can also be joined.
set1 = {"a", "b"}
set2 = {"c", "d"}
set3 = {"e", "f"}
result = set1.union(set2, set3)
print(result)
# Output:
# {'a', 'b', 'c', 'd', 'e', 'f'}
# The | Operator
# The union operator (|) performs the same operation as union().
set1 = {"apple", "banana"}
set2 = {"banana", "cherry"}
print(set1 | set2)
# Output:
# {'apple', 'banana', 'cherry'}
# update()
# The update() method adds all elements of another iterable into
# the current set. Unlike union(), it modifies the original set.
set1 = {"apple", "banana"}
set2 = {"orange", "kiwi"}
set1.update(set2)
print(set1)
# Output:
# {'apple', 'banana', 'orange', 'kiwi'}
# Difference between union() and update()
# union()
# • Returns a new set.
# • Original sets remain unchanged.
# update()
# • Modifies the original set.
# • Returns None.
# intersection()
# The intersection() method returns a new set containing only the
# common elements present in both sets.
set1 = {"apple", "banana", "cherry"}
set2 = {"banana", "mango", "apple"}
set3 = set1.intersection(set2)
print(set3)
# Output:
# {'apple', 'banana'}
# Syntax
set3 = set1.intersection(set2)
# The & Operator
# The & operator performs the same operation as intersection().
print(set1 & set2)
# Output:
# {'apple', 'banana'}
# intersection_update()
# intersection_update() keeps only the common elements in the
# original set.
set1 = {"apple", "banana", "cherry"}
set2 = {"banana", "apple", "kiwi"}
set1.intersection_update(set2)
print(set1)
# Output:
# {'apple', 'banana'}
# Unlike intersection(), no new set is created.
# difference()
# The difference() method returns a new set containing the elements
# that exist in the first set but not in the second.
set1 = {"apple", "banana", "cherry"}
set2 = {"banana", "kiwi"}
set3 = set1.difference(set2)
print(set3)
# Output:
# {'apple', 'cherry'}
# Syntax
set3 = set1.difference(set2)
# The - Operator
print(set1 - set2)
# Output:
# {'apple', 'cherry'}
# difference_update()
# Removes all common elements from the original set.
set1 = {"apple", "banana", "cherry"}
set2 = {"banana", "kiwi"}
set1.difference_update(set2)
print(set1)
# Output:
# {'apple', 'cherry'}
# Unlike difference(), the original set is modified.
# symmetric_difference()
# Returns a new set containing elements that are present in either
# set but not in both.
set1 = {"apple", "banana", "cherry"}
set2 = {"banana", "kiwi", "orange"}
set3 = set1.symmetric_difference(set2)
print(set3)
# Output:
# {'apple', 'cherry', 'kiwi', 'orange'}
# Common elements are removed.
# Syntax
set3 = set1.symmetric_difference(set2)
# The ^ Operator
print(set1 ^ set2)
# Output:
# {'apple', 'cherry', 'kiwi', 'orange'}
# symmetric_difference_update()
# Updates the original set with the symmetric difference.
set1 = {"apple", "banana", "cherry"}
set2 = {"banana", "kiwi", "orange"}
set1.symmetric_difference_update(set2)
print(set1)
# Output:
# {'apple', 'cherry', 'kiwi', 'orange'}
# Comparison of Set Operations
# union()
# Returns all unique elements.
# intersection()
# Returns only common elements.
# difference()
# Returns elements present in the first set only.
# symmetric_difference()
# Returns elements present in either set but not both.
# Interview Insight:
# Methods ending with "_update" modify the original set.
# Methods without "_update" return a new set.
# Example:
# union()                    -> New Set
# intersection()             -> New Set
# difference()               -> New Set
# symmetric_difference()     -> New Set
# update()                       -> Modifies Original
# intersection_update()          -> Modifies Original
# difference_update()            -> Modifies Original
# symmetric_difference_update()  -> Modifies Original
# Copying Sets
# Assigning one set to another does not create a copy.
# Both variables refer to the same set object.
set1 = {"apple", "banana", "cherry"}
set2 = set1
set2.add("orange")
print(set1)
print(set2)
# Output:
# {'apple', 'banana', 'cherry', 'orange'}
# {'apple', 'banana', 'cherry', 'orange'}
# copy()
# The copy() method creates a shallow copy of the set.
# Since sets can only store immutable objects, a shallow copy behaves like an independent copy.
set1 = {"apple", "banana", "cherry"}
set2 = set1.copy()
set2.add("orange")
print(set1)
print(set2)
# Output:
# {'apple', 'banana', 'cherry'}
# {'apple', 'banana', 'cherry', 'orange'}
# Syntax
new_set = set_name.copy()
# issubset()
# The issubset() method returns True if every element of the set
# exists in another set.
set1 = {"apple", "banana"}
set2 = {"apple", "banana", "cherry"}
print(set1.issubset(set2))
# Output:
# True
print(set2.issubset(set1))
# Output:
# False
# Syntax
set1.issubset(set2)
# issuperset()
# The issuperset() method returns True if the set contains
# all elements of another set.
set1 = {"apple", "banana", "cherry"}
set2 = {"apple", "banana"}
print(set1.issuperset(set2))
# Output:
# True
print(set2.issuperset(set1))
# Output:
# False
# Syntax
set1.issuperset(set2)
# isdisjoint()
# The isdisjoint() method returns True if both sets have
# no common elements.
set1 = {"apple", "banana"}
set2 = {"kiwi", "orange"}
print(set1.isdisjoint(set2))
# Output:
# True
set3 = {"banana", "kiwi"}
print(set1.isdisjoint(set3))
# Output:
# False
# Syntax
set1.isdisjoint(set2)
# frozenset()
# A frozenset is an immutable version of a set.
# Items cannot be added or removed after creation.
fruits = frozenset({"apple", "banana", "cherry"})
print(fruits)
# Output:
# frozenset({'apple', 'banana', 'cherry'})
# fruits.add("orange")
# Output:
# AttributeError: 'frozenset' object has no attribute 'add'
# frozensets are hashable and can be used as dictionary keys
# or as elements of another set.
# Set Comprehension
# Set comprehension is used to create a new set in a single line.
# Syntax
# {expression for item in iterable}
numbers = {x for x in range(1, 6)}
print(numbers)
# Output:
# {1, 2, 3, 4, 5}
# Using a condition
even = {x for x in range(10) if x % 2 == 0}
print(even)
# Output:
# {0, 2, 4, 6, 8}
# Set comprehension automatically removes duplicate values.
numbers = {x % 3 for x in range(10)}
print(numbers)
# Output:
# {0, 1, 2}
# Interview Insight:
# Set comprehensions are similar to list comprehensions, but they
# always produce unique values.
# -------------------------------------------------------------
# Built-in Functions
# -------------------------------------------------------------
# len()
# Returns the number of elements in the set.
fruits = {"apple", "banana", "cherry"}
print(len(fruits))
# Output:
# 3
# max()
# Returns the largest element.
numbers = {10, 30, 20}
print(max(numbers))
# Output:
# 30
# min()
# Returns the smallest element.
print(min(numbers))
# Output:
# 10
# sum()
# Returns the sum of all numeric elements.
numbers = {10, 20, 30}
print(sum(numbers))
# Output:
# 60
# sorted()
# Returns a sorted list.
# It does not return a set.
numbers = {40, 20, 10, 30}
print(sorted(numbers))
# Output:
# [10, 20, 30, 40]
# any()
# Returns True if at least one element evaluates to True.
values = {0, False, 5}
print(any(values))
# Output:
# True
# all()
# Returns True only if all elements evaluate to True.
values = {1, 2, 3}
print(all(values))
# Output:
# True
values = {1, 0, 3}
print(all(values))
# Output:
# False
# -------------------------------------------------------------
# Complete Set Methods
# -------------------------------------------------------------
# add(item)
# Adds one element.
# clear()
# Removes all elements.
# copy()
# Returns a shallow copy.
# difference()
# Returns elements present only in the first set.
# difference_update()
# Removes common elements from the original set.
# discard(item)
# Removes an item if present.
# intersection()
# Returns common elements.
# intersection_update()
# Keeps only common elements in the original set.
# isdisjoint()
# Returns True if two sets have no common elements.
# issubset()
# Returns True if all elements exist in another set.
# issuperset()
# Returns True if the set contains another set.
# pop()
# Removes and returns an arbitrary element.
# remove(item)
# Removes the specified item.
# symmetric_difference()
# Returns elements that are present in either set but not both.
# symmetric_difference_update()
# Updates the original set with the symmetric difference.
# union()
# Returns a new set containing all unique elements.
# update()
# Adds all elements from another iterable into the original set.
# -------------------------------------------------------------
# Time Complexity (Average Case)
# -------------------------------------------------------------
# Searching using 'in'             -> O(1)
# add()                            -> O(1)
# remove()                         -> O(1)
# discard()                        -> O(1)
# pop()                            -> O(1)
# union()                          -> O(len(set1) + len(set2))
# intersection()                   -> O(min(len(set1), len(set2)))
# difference()                     -> O(len(set1))
# copy()                           -> O(n)
# Interview Insight:
# Sets are implemented using hash tables.
# This is why searching is generally much faster than searching in a list.
# End of Python Sets